### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by yashuk803** [yashuk803/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by FesenkoE** [comment]
https://github.com/vdiakiv/homepage/issues/4

**Comment by FesenkoE** [comment]
Имею опыт в разрабоке веб-сайтов на PHP. Создание корпоративного приложения с использованием технологий LAMP и LEMP, JavaScript, JQuery, CSS, HTML, Laravel, Yii2 Framework, GIT. Возможность многозадачности, быстро реагировать на перенос приоритетов и соблюдение сроков.
Уверенный в себе с позитивным настроем «can-do». Постоянный наблюдаю за отраслевыми тенденциями, технологиями и стандартами. Опыт Solid Web-разработки с использованием OOP, PHP, AJAX, MySQL, JavaScript, XML, HTML и CSS. Небольшой опыт в построении сервисной архитектуры.
Недостатки: излишняя прямота, привычка говорить правду в глаза; безотказность; гиперактивность; необходимость внешней мотивации; завышенное чувство ответственности.
