### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by yashuk803** [yashuk803/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by FesenkoE** [comment]
https://github.com/vdiakiv/homepage/issues/4

**Comment by FesenkoE** [comment]
https://www.facebook.com/fesenkoe
