### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by yashuk803** [yashuk803/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by FesenkoE** [comment]
Директор 
окт 2007 - настоящее время (11 лет 8 мес)

Гринев и К(http://www.grinev-i-k.ucoz.ru) 
до 20 сотрудников Интернет

С 2007 г. «Гринев и К» - Директор.Агентство массовых коммуникаций (АМК - Москва) ."FinMarkt AG" , Германия, адрес: Rheinstr.22, 65185 Wiesbade.Агент Приват Банк-а.  ООО «Герметик - Универсал».  Orlov & Wehmann Systems.Российский Технический Центр №1.  Интернет-Магазин "ANGEL"."МODA-Sheek". "РемБытТехника". ЗАТ «Промважмаш».- 2017 «Moda-Stile». IT-Veb - Продвижение.

Программист. Специалист.
авг 1999 - апр 2004 (4 года 9 мес)

Интерпайп, трубопрокатный завод Карла Либнехта
Промышленность и Производство

Директор по экономической безопасности
янв 1999 - мар 1999 (3 мес)

Центральный универмаг г. Днепропетровска
от 100 до 250 сотрудников Торговля розничная / Retail

Центральный универмаг г. Днепропетровска (торговля), г. Днепропетровск

разработка стратегии экономической безопасности - временная - по договору.
Коммерческий директор 
апр 1994 - окт 1998 (4 года 7 мес)

Синегри
до 20 сотрудников Торговля оптовая / Дистрибуция / Импорт-экспорт

ОО фирма "Синегри" (коммерция), г. Днепропетровск
Оптовые поставки трубного проката.
Организация торговли трубопрокатным товаром - поставки с заводов Украины и Казани (Россия) в Норильск. Переговоры на заводах - производителях. С ЖД - и авто перевозчиками. Доставка товара до Одессы и Мурманска.
Переговоры в портах - отправка товара.
Коммерческий директор
ноя 1990 - ноя 1993 (3 года 1 мес)

РУМА
от 20 до 50 сотрудников Торговля оптовая / Дистрибуция / Импорт-экспорт

Организация кредитной линии для фирмы и трех дочерних фирм.
Ведущий программист
сен 1987 - янв 1992 (4 года 5 мес)

ЮМЗ, Союз Менеджеров СССР
от 250 до 500 сотрудников IT - разработка ПО

Союз Менеджеров СССР (менеджмент),г. Днепропетровск
март-май - 3-м курс Высшего Менеджмента при
МГУ им. М. В. Ломоносова- г. Москва. Магистр.
Образование
Московский государственный университет имени М. В. Ломоносова(Москва, Россия) 
Год окончания 1991

Высший менеджмент, магистр
Днепропетровский государственный университет(Днепропетровск, Украина) 
Год окончания 1987

Экономический факультет, экономическая кибернетика, специалист
СШ-№43 (Днепропетровск) 
Год окончания 1982

математический класс, 1982 г. действительный член Малой Академии наук учеников г.Днепропетровска /математика.
