### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by yashuk803** [yashuk803/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by FesenkoE** [comment]
Владение языками
Английский- выше среднего

Курсы, тренинги, сертификаты
Курс PHP, Академия Hillel(Днепр)

Год окончания 2019

Дополнительная информация:

Семейное положение: не женат, один ребенок. Наличие загранпаспорта. 

Водительское удостоверение категории "В", опыт вождения 2 года
